stages:
  - build
  - test
  - e2e
  - deploy

docker-build:
  env:
    REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    TAG: development-${CI_PIPELINE_ID}
  script:
    - docker build -t ${REGISTRY}:${TAG} .
    - docker push ${REGISTRY}:${TAG}

