
stages:
  - test
  - build binaries
  - build docker
  - e2e
  - deploy

include:
  - template: Workflows/MergeRequest-Pipelines.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - local: /.gitlab/ci/variables.gitlab-ci.yml
  - local: /.gitlab/ci/test.gitlab-ci.yml
  - local: /.gitlab/ci/build-binaries.gitlab-ci.yml
  - local: /.gitlab/ci/build-docker.gitlab-ci.yml
  - local: /.gitlab/ci/e2e.gitlab-ci.yml
  - local: /.gitlab/ci/deploy.gitlab-ci.yml
