// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.1
// 	protoc        v4.22.2
// source: expression.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Value is a materialized value that represents a fully evaluated expression
// It supports various data types similar to JSON plus function references
type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Only one of these types can be present at a time
	//
	// Types that are assignable to Type:
	//
	//	*Value_String_
	//	*Value_Number
	//	*Value_Boolean
	//	*Value_Array_
	//	*Value_Map_
	Type isValue_Type `protobuf_oneof:"type"`
	// Sensitive determines if this value contains sensitive information
	// Sensitivity is persistent across all operations and is propagated
	// when values are transformed or combined
	Sensitive *bool `protobuf:"varint,7,opt,name=sensitive,proto3,oneof" json:"sensitive,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{0}
}

func (m *Value) GetType() isValue_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Value) GetString_() string {
	if x, ok := x.GetType().(*Value_String_); ok {
		return x.String_
	}
	return ""
}

func (x *Value) GetNumber() float64 {
	if x, ok := x.GetType().(*Value_Number); ok {
		return x.Number
	}
	return 0
}

func (x *Value) GetBoolean() bool {
	if x, ok := x.GetType().(*Value_Boolean); ok {
		return x.Boolean
	}
	return false
}

func (x *Value) GetArray() *Value_Array {
	if x, ok := x.GetType().(*Value_Array_); ok {
		return x.Array
	}
	return nil
}

func (x *Value) GetMap() *Value_Map {
	if x, ok := x.GetType().(*Value_Map_); ok {
		return x.Map
	}
	return nil
}

func (x *Value) GetSensitive() bool {
	if x != nil && x.Sensitive != nil {
		return *x.Sensitive
	}
	return false
}

type isValue_Type interface {
	isValue_Type()
}

type Value_String_ struct {
	// String value for text data
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Number struct {
	// Numeric value for floating point numbers
	Number float64 `protobuf:"fixed64,2,opt,name=number,proto3,oneof"`
}

type Value_Boolean struct {
	// Boolean value for true/false conditions
	Boolean bool `protobuf:"varint,3,opt,name=boolean,proto3,oneof"`
}

type Value_Array_ struct {
	// Array of nested Values for ordered collections
	Array *Value_Array `protobuf:"bytes,4,opt,name=array,proto3,oneof"`
}

type Value_Map_ struct {
	// Map of string keys to Values for structured data
	Map *Value_Map `protobuf:"bytes,5,opt,name=map,proto3,oneof"`
}

func (*Value_String_) isValue_Type() {}

func (*Value_Number) isValue_Type() {}

func (*Value_Boolean) isValue_Type() {}

func (*Value_Array_) isValue_Type() {}

func (*Value_Map_) isValue_Type() {}

// An expression is a value which requires evaluation with an environment
// Expressions allow for dynamic computation and late binding of values
type Expression struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Version of the expression definition for protocol compatibility
	Version *Version `protobuf:"bytes,1,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// The operation to perform
	//
	// Types that are assignable to Op:
	//
	//	*Expression_Literal
	//	*Expression_Environment
	//	*Expression_Read
	//	*Expression_Write
	//	*Expression_Concat
	Op isExpression_Op `protobuf_oneof:"op"`
	// Debug metadata for tracing back to source code
	DebugMetadata *DebugMetadata `protobuf:"bytes,7,opt,name=debug_metadata,json=debugMetadata,proto3,oneof" json:"debug_metadata,omitempty"`
}

func (x *Expression) Reset() {
	*x = Expression{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Expression) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expression) ProtoMessage() {}

func (x *Expression) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expression.ProtoReflect.Descriptor instead.
func (*Expression) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{1}
}

func (x *Expression) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (m *Expression) GetOp() isExpression_Op {
	if m != nil {
		return m.Op
	}
	return nil
}

func (x *Expression) GetLiteral() *Value {
	if x, ok := x.GetOp().(*Expression_Literal); ok {
		return x.Literal
	}
	return nil
}

func (x *Expression) GetEnvironment() *OpEnvironment {
	if x, ok := x.GetOp().(*Expression_Environment); ok {
		return x.Environment
	}
	return nil
}

func (x *Expression) GetRead() *OpRead {
	if x, ok := x.GetOp().(*Expression_Read); ok {
		return x.Read
	}
	return nil
}

func (x *Expression) GetWrite() *OpWrite {
	if x, ok := x.GetOp().(*Expression_Write); ok {
		return x.Write
	}
	return nil
}

func (x *Expression) GetConcat() *OpConcat {
	if x, ok := x.GetOp().(*Expression_Concat); ok {
		return x.Concat
	}
	return nil
}

func (x *Expression) GetDebugMetadata() *DebugMetadata {
	if x != nil {
		return x.DebugMetadata
	}
	return nil
}

type isExpression_Op interface {
	isExpression_Op()
}

type Expression_Literal struct {
	// Literal is an expression which has been fully evaluated
	Literal *Value `protobuf:"bytes,2,opt,name=literal,proto3,oneof"`
}

type Expression_Environment struct {
	// OpEnvironment returns the current proto Environment
	Environment *OpEnvironment `protobuf:"bytes,3,opt,name=environment,proto3,oneof"`
}

type Expression_Read struct {
	// OpRead reads into a value
	Read *OpRead `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type Expression_Write struct {
	// OpWrite writes into a value
	Write *OpWrite `protobuf:"bytes,5,opt,name=write,proto3,oneof"`
}

type Expression_Concat struct {
	// Concat concatenates multiple compatible expressions
	Concat *OpConcat `protobuf:"bytes,6,opt,name=concat,proto3,oneof"`
}

func (*Expression_Literal) isExpression_Op() {}

func (*Expression_Environment) isExpression_Op() {}

func (*Expression_Read) isExpression_Op() {}

func (*Expression_Write) isExpression_Op() {}

func (*Expression_Concat) isExpression_Op() {}

// OpEnvironment returns the current proto Environment
// This is used to access the environment context during expression evaluation
type OpEnvironment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpEnvironment) Reset() {
	*x = OpEnvironment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpEnvironment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpEnvironment) ProtoMessage() {}

func (x *OpEnvironment) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpEnvironment.ProtoReflect.Descriptor instead.
func (*OpEnvironment) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{2}
}

// OpRead reads into a value
// This is used to access nested values within a structure
type OpRead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Value is an Expression to be evaluated until it is a Value
	// This is the base value to read from
	Value *Expression `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// Path is the subtree of the value to return
	// Each Expression in the path is evaluated to determine the path element
	// Path elements must be valid for the structure being accessed:
	// - For arrays: numeric indices
	// - For maps: string keys
	// - Attempts to access invalid paths will result in evaluation errors
	Path []*Expression `protobuf:"bytes,2,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *OpRead) Reset() {
	*x = OpRead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRead) ProtoMessage() {}

func (x *OpRead) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRead.ProtoReflect.Descriptor instead.
func (*OpRead) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{3}
}

func (x *OpRead) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OpRead) GetPath() []*Expression {
	if x != nil {
		return x.Path
	}
	return nil
}

// OpWrite writes into a value
// This is used to modify values within a structure
type OpWrite struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Value is an Expression to be evaluated until it is a Value
	// This is the value to write
	Value *Expression `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	// Into is the structure into which to write the Value
	// This is the base value to modify
	Into *Expression `protobuf:"bytes,2,opt,name=into,proto3,oneof" json:"into,omitempty"`
	// Path is where to write the value
	// Each Expression in the path is evaluated to determine the path element
	// Path elements must be valid for the structure being modified:
	// - For arrays: numeric indices
	// - For maps: string keys
	// - Attempts to access invalid paths will result in evaluation errors
	Path []*Expression `protobuf:"bytes,3,rep,name=path,proto3" json:"path,omitempty"`
}

func (x *OpWrite) Reset() {
	*x = OpWrite{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpWrite) ProtoMessage() {}

func (x *OpWrite) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpWrite.ProtoReflect.Descriptor instead.
func (*OpWrite) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{4}
}

func (x *OpWrite) GetValue() *Expression {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OpWrite) GetInto() *Expression {
	if x != nil {
		return x.Into
	}
	return nil
}

func (x *OpWrite) GetPath() []*Expression {
	if x != nil {
		return x.Path
	}
	return nil
}

// OpConcat concatenates multiple compatible expressions
// This allows for combining values of the same type
type OpConcat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Expression(s) are the expressions to concatenate
	// Strings are compatible with strings
	// Structs are compatible with structs (each overlaying the previous)
	// Arrays are compatible with arrays (each extending the array)
	// All other types return an error
	Expression []*Expression `protobuf:"bytes,1,rep,name=expression,proto3" json:"expression,omitempty"`
}

func (x *OpConcat) Reset() {
	*x = OpConcat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpConcat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpConcat) ProtoMessage() {}

func (x *OpConcat) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpConcat.ProtoReflect.Descriptor instead.
func (*OpConcat) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{5}
}

func (x *OpConcat) GetExpression() []*Expression {
	if x != nil {
		return x.Expression
	}
	return nil
}

// Array is a wrapper for an array of Values
type Value_Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Value_Array) Reset() {
	*x = Value_Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Array) ProtoMessage() {}

func (x *Value_Array) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Array.ProtoReflect.Descriptor instead.
func (*Value_Array) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Value_Array) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Map is a wrapper for a map of string to Value
type Value_Map struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values map[string]*Value `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Value_Map) Reset() {
	*x = Value_Map{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value_Map) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value_Map) ProtoMessage() {}

func (x *Value_Map) ProtoReflect() protoreflect.Message {
	mi := &file_expression_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value_Map.ProtoReflect.Descriptor instead.
func (*Value_Map) Descriptor() ([]byte, []int) {
	return file_expression_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Value_Map) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_expression_proto protoreflect.FileDescriptor

var file_expression_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x03, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x48, 0x00, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x12, 0x24,
	0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70, 0x48, 0x00, 0x52,
	0x03, 0x6d, 0x61, 0x70, 0x12, 0x21, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x1a, 0x2d, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79,
	0x12, 0x24, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x84, 0x01, 0x0a, 0x03, 0x4d, 0x61, 0x70, 0x12, 0x34,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x4d, 0x61, 0x70,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x1a, 0x47, 0x0a, 0x0b, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x06, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x22, 0xfe, 0x02, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x28, 0x0a, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x48, 0x00, 0x52, 0x07, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x38, 0x0a, 0x0b, 0x65,
	0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x45, 0x6e, 0x76, 0x69, 0x72,
	0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x52, 0x65,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65, 0x61, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4f, 0x70, 0x57, 0x72, 0x69, 0x74, 0x65, 0x48, 0x00, 0x52, 0x05, 0x77, 0x72, 0x69,
	0x74, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x43, 0x6f, 0x6e,
	0x63, 0x61, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x12, 0x40, 0x0a,
	0x0e, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x02, 0x52, 0x0d, 0x64,
	0x65, 0x62, 0x75, 0x67, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42,
	0x04, 0x0a, 0x02, 0x6f, 0x70, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x5f, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x4f, 0x70, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x67, 0x0a, 0x06, 0x4f, 0x70, 0x52, 0x65, 0x61, 0x64, 0x12,
	0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x9d,
	0x01, 0x0a, 0x07, 0x4f, 0x70, 0x57, 0x72, 0x69, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x2a, 0x0a, 0x04, 0x69, 0x6e, 0x74, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x01, 0x52, 0x04, 0x69, 0x6e, 0x74,
	0x6f, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x74, 0x6f, 0x22, 0x3d,
	0x0a, 0x08, 0x4f, 0x70, 0x43, 0x6f, 0x6e, 0x63, 0x61, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_expression_proto_rawDescOnce sync.Once
	file_expression_proto_rawDescData = file_expression_proto_rawDesc
)

func file_expression_proto_rawDescGZIP() []byte {
	file_expression_proto_rawDescOnce.Do(func() {
		file_expression_proto_rawDescData = protoimpl.X.CompressGZIP(file_expression_proto_rawDescData)
	})
	return file_expression_proto_rawDescData
}

var file_expression_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_expression_proto_goTypes = []interface{}{
	(*Value)(nil),         // 0: proto.Value
	(*Expression)(nil),    // 1: proto.Expression
	(*OpEnvironment)(nil), // 2: proto.OpEnvironment
	(*OpRead)(nil),        // 3: proto.OpRead
	(*OpWrite)(nil),       // 4: proto.OpWrite
	(*OpConcat)(nil),      // 5: proto.OpConcat
	(*Value_Array)(nil),   // 6: proto.Value.Array
	(*Value_Map)(nil),     // 7: proto.Value.Map
	nil,                   // 8: proto.Value.Map.ValuesEntry
	(*Version)(nil),       // 9: proto.Version
	(*DebugMetadata)(nil), // 10: proto.DebugMetadata
}
var file_expression_proto_depIdxs = []int32{
	6,  // 0: proto.Value.array:type_name -> proto.Value.Array
	7,  // 1: proto.Value.map:type_name -> proto.Value.Map
	9,  // 2: proto.Expression.version:type_name -> proto.Version
	0,  // 3: proto.Expression.literal:type_name -> proto.Value
	2,  // 4: proto.Expression.environment:type_name -> proto.OpEnvironment
	3,  // 5: proto.Expression.read:type_name -> proto.OpRead
	4,  // 6: proto.Expression.write:type_name -> proto.OpWrite
	5,  // 7: proto.Expression.concat:type_name -> proto.OpConcat
	10, // 8: proto.Expression.debug_metadata:type_name -> proto.DebugMetadata
	1,  // 9: proto.OpRead.value:type_name -> proto.Expression
	1,  // 10: proto.OpRead.path:type_name -> proto.Expression
	1,  // 11: proto.OpWrite.value:type_name -> proto.Expression
	1,  // 12: proto.OpWrite.into:type_name -> proto.Expression
	1,  // 13: proto.OpWrite.path:type_name -> proto.Expression
	1,  // 14: proto.OpConcat.expression:type_name -> proto.Expression
	0,  // 15: proto.Value.Array.values:type_name -> proto.Value
	8,  // 16: proto.Value.Map.values:type_name -> proto.Value.Map.ValuesEntry
	0,  // 17: proto.Value.Map.ValuesEntry.value:type_name -> proto.Value
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_expression_proto_init() }
func file_expression_proto_init() {
	if File_expression_proto != nil {
		return
	}
	file_metadata_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_expression_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Expression); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpEnvironment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpRead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpWrite); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpConcat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value_Map); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_expression_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Value_String_)(nil),
		(*Value_Number)(nil),
		(*Value_Boolean)(nil),
		(*Value_Array_)(nil),
		(*Value_Map_)(nil),
	}
	file_expression_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Expression_Literal)(nil),
		(*Expression_Environment)(nil),
		(*Expression_Read)(nil),
		(*Expression_Write)(nil),
		(*Expression_Concat)(nil),
	}
	file_expression_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_expression_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expression_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expression_proto_goTypes,
		DependencyIndexes: file_expression_proto_depIdxs,
		MessageInfos:      file_expression_proto_msgTypes,
	}.Build()
	File_expression_proto = out.File
	file_expression_proto_rawDesc = nil
	file_expression_proto_goTypes = nil
	file_expression_proto_depIdxs = nil
}
