// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: step.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StepRunner_Run_FullMethodName         = "/proto.StepRunner/Run"
	StepRunner_FollowSteps_FullMethodName = "/proto.StepRunner/FollowSteps"
	StepRunner_Close_FullMethodName       = "/proto.StepRunner/Close"
	StepRunner_FollowLogs_FullMethodName  = "/proto.StepRunner/FollowLogs"
	StepRunner_Status_FullMethodName      = "/proto.StepRunner/Status"
)

// StepRunnerClient is the client API for StepRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepRunnerClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	FollowSteps(ctx context.Context, in *FollowStepsRequest, opts ...grpc.CallOption) (StepRunner_FollowStepsClient, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (StepRunner_FollowLogsClient, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type stepRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewStepRunnerClient(cc grpc.ClientConnInterface) StepRunnerClient {
	return &stepRunnerClient{cc}
}

func (c *stepRunnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, StepRunner_Run_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) FollowSteps(ctx context.Context, in *FollowStepsRequest, opts ...grpc.CallOption) (StepRunner_FollowStepsClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[0], StepRunner_FollowSteps_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowStepsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowStepsClient interface {
	Recv() (*FollowStepsResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowStepsClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowStepsClient) Recv() (*FollowStepsResponse, error) {
	m := new(FollowStepsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, StepRunner_Close_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (StepRunner_FollowLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[1], StepRunner_FollowLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowLogsClient interface {
	Recv() (*FollowLogsResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowLogsClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowLogsClient) Recv() (*FollowLogsResponse, error) {
	m := new(FollowLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, StepRunner_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepRunnerServer is the server API for StepRunner service.
// All implementations must embed UnimplementedStepRunnerServer
// for forward compatibility
type StepRunnerServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	FollowSteps(*FollowStepsRequest, StepRunner_FollowStepsServer) error
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	FollowLogs(*FollowLogsRequest, StepRunner_FollowLogsServer) error
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedStepRunnerServer()
}

// UnimplementedStepRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedStepRunnerServer struct {
}

func (UnimplementedStepRunnerServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStepRunnerServer) FollowSteps(*FollowStepsRequest, StepRunner_FollowStepsServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowSteps not implemented")
}
func (UnimplementedStepRunnerServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedStepRunnerServer) FollowLogs(*FollowLogsRequest, StepRunner_FollowLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowLogs not implemented")
}
func (UnimplementedStepRunnerServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedStepRunnerServer) mustEmbedUnimplementedStepRunnerServer() {}

// UnsafeStepRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepRunnerServer will
// result in compilation errors.
type UnsafeStepRunnerServer interface {
	mustEmbedUnimplementedStepRunnerServer()
}

func RegisterStepRunnerServer(s grpc.ServiceRegistrar, srv StepRunnerServer) {
	s.RegisterService(&StepRunner_ServiceDesc, srv)
}

func _StepRunner_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_FollowSteps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowStepsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).FollowSteps(m, &stepRunnerFollowStepsServer{stream})
}

type StepRunner_FollowStepsServer interface {
	Send(*FollowStepsResponse) error
	grpc.ServerStream
}

type stepRunnerFollowStepsServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowStepsServer) Send(m *FollowStepsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_FollowLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).FollowLogs(m, &stepRunnerFollowLogsServer{stream})
}

type StepRunner_FollowLogsServer interface {
	Send(*FollowLogsResponse) error
	grpc.ServerStream
}

type stepRunnerFollowLogsServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowLogsServer) Send(m *FollowLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepRunner_ServiceDesc is the grpc.ServiceDesc for StepRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepRunner",
	HandlerType: (*StepRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StepRunner_Run_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StepRunner_Close_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _StepRunner_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FollowSteps",
			Handler:       _StepRunner_FollowSteps_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FollowLogs",
			Handler:       _StepRunner_FollowLogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "step.proto",
}
