// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: step.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StepRunner_Run_FullMethodName      = "/proto.StepRunner/Run"
	StepRunner_Follow_FullMethodName   = "/proto.StepRunner/Follow"
	StepRunner_FollowIO_FullMethodName = "/proto.StepRunner/FollowIO"
	StepRunner_Cancel_FullMethodName   = "/proto.StepRunner/Cancel"
)

// StepRunnerClient is the client API for StepRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepRunnerClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (StepRunner_FollowClient, error)
	FollowIO(ctx context.Context, in *FollowIORequest, opts ...grpc.CallOption) (StepRunner_FollowIOClient, error)
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type stepRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewStepRunnerClient(cc grpc.ClientConnInterface) StepRunnerClient {
	return &stepRunnerClient{cc}
}

func (c *stepRunnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, StepRunner_Run_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (StepRunner_FollowClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[0], StepRunner_Follow_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowClient interface {
	Recv() (*FollowResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowClient) Recv() (*FollowResponse, error) {
	m := new(FollowResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) FollowIO(ctx context.Context, in *FollowIORequest, opts ...grpc.CallOption) (StepRunner_FollowIOClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[1], StepRunner_FollowIO_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowIOClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowIOClient interface {
	Recv() (*FollowIOResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowIOClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowIOClient) Recv() (*FollowIOResponse, error) {
	m := new(FollowIOResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, StepRunner_Cancel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepRunnerServer is the server API for StepRunner service.
// All implementations must embed UnimplementedStepRunnerServer
// for forward compatibility
type StepRunnerServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	Follow(*FollowRequest, StepRunner_FollowServer) error
	FollowIO(*FollowIORequest, StepRunner_FollowIOServer) error
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	mustEmbedUnimplementedStepRunnerServer()
}

// UnimplementedStepRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedStepRunnerServer struct {
}

func (UnimplementedStepRunnerServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStepRunnerServer) Follow(*FollowRequest, StepRunner_FollowServer) error {
	return status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedStepRunnerServer) FollowIO(*FollowIORequest, StepRunner_FollowIOServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowIO not implemented")
}
func (UnimplementedStepRunnerServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedStepRunnerServer) mustEmbedUnimplementedStepRunnerServer() {}

// UnsafeStepRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepRunnerServer will
// result in compilation errors.
type UnsafeStepRunnerServer interface {
	mustEmbedUnimplementedStepRunnerServer()
}

func RegisterStepRunnerServer(s grpc.ServiceRegistrar, srv StepRunnerServer) {
	s.RegisterService(&StepRunner_ServiceDesc, srv)
}

func _StepRunner_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_Follow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).Follow(m, &stepRunnerFollowServer{stream})
}

type StepRunner_FollowServer interface {
	Send(*FollowResponse) error
	grpc.ServerStream
}

type stepRunnerFollowServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowServer) Send(m *FollowResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_FollowIO_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowIORequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).FollowIO(m, &stepRunnerFollowIOServer{stream})
}

type StepRunner_FollowIOServer interface {
	Send(*FollowIOResponse) error
	grpc.ServerStream
}

type stepRunnerFollowIOServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowIOServer) Send(m *FollowIOResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepRunner_ServiceDesc is the grpc.ServiceDesc for StepRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepRunner",
	HandlerType: (*StepRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StepRunner_Run_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _StepRunner_Cancel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Follow",
			Handler:       _StepRunner_Follow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FollowIO",
			Handler:       _StepRunner_FollowIO_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "step.proto",
}
