// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: step.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StepRunner_Run_FullMethodName         = "/proto.StepRunner/Run"
	StepRunner_FollowSteps_FullMethodName = "/proto.StepRunner/FollowSteps"
	StepRunner_Close_FullMethodName       = "/proto.StepRunner/Close"
	StepRunner_FollowLogs_FullMethodName  = "/proto.StepRunner/FollowLogs"
	StepRunner_Status_FullMethodName      = "/proto.StepRunner/Status"
	StepRunner_RunUp_FullMethodName       = "/proto.StepRunner/RunUp"
)

// StepRunnerClient is the client API for StepRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepRunnerClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
	FollowSteps(ctx context.Context, in *FollowStepsRequest, opts ...grpc.CallOption) (StepRunner_FollowStepsClient, error)
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (StepRunner_FollowLogsClient, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	RunUp(ctx context.Context, opts ...grpc.CallOption) (StepRunner_RunUpClient, error)
}

type stepRunnerClient struct {
	cc grpc.ClientConnInterface
}

func NewStepRunnerClient(cc grpc.ClientConnInterface) StepRunnerClient {
	return &stepRunnerClient{cc}
}

func (c *stepRunnerClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, StepRunner_Run_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) FollowSteps(ctx context.Context, in *FollowStepsRequest, opts ...grpc.CallOption) (StepRunner_FollowStepsClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[0], StepRunner_FollowSteps_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowStepsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowStepsClient interface {
	Recv() (*FollowStepsResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowStepsClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowStepsClient) Recv() (*FollowStepsResponse, error) {
	m := new(FollowStepsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, StepRunner_Close_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) FollowLogs(ctx context.Context, in *FollowLogsRequest, opts ...grpc.CallOption) (StepRunner_FollowLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[1], StepRunner_FollowLogs_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerFollowLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StepRunner_FollowLogsClient interface {
	Recv() (*FollowLogsResponse, error)
	grpc.ClientStream
}

type stepRunnerFollowLogsClient struct {
	grpc.ClientStream
}

func (x *stepRunnerFollowLogsClient) Recv() (*FollowLogsResponse, error) {
	m := new(FollowLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stepRunnerClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, StepRunner_Status_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepRunnerClient) RunUp(ctx context.Context, opts ...grpc.CallOption) (StepRunner_RunUpClient, error) {
	stream, err := c.cc.NewStream(ctx, &StepRunner_ServiceDesc.Streams[2], StepRunner_RunUp_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &stepRunnerRunUpClient{stream}
	return x, nil
}

type StepRunner_RunUpClient interface {
	Send(*RunUpResponse) error
	Recv() (*RunUpRequest, error)
	grpc.ClientStream
}

type stepRunnerRunUpClient struct {
	grpc.ClientStream
}

func (x *stepRunnerRunUpClient) Send(m *RunUpResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *stepRunnerRunUpClient) Recv() (*RunUpRequest, error) {
	m := new(RunUpRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StepRunnerServer is the server API for StepRunner service.
// All implementations must embed UnimplementedStepRunnerServer
// for forward compatibility
type StepRunnerServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	FollowSteps(*FollowStepsRequest, StepRunner_FollowStepsServer) error
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	FollowLogs(*FollowLogsRequest, StepRunner_FollowLogsServer) error
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	RunUp(StepRunner_RunUpServer) error
	mustEmbedUnimplementedStepRunnerServer()
}

// UnimplementedStepRunnerServer must be embedded to have forward compatible implementations.
type UnimplementedStepRunnerServer struct {
}

func (UnimplementedStepRunnerServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedStepRunnerServer) FollowSteps(*FollowStepsRequest, StepRunner_FollowStepsServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowSteps not implemented")
}
func (UnimplementedStepRunnerServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedStepRunnerServer) FollowLogs(*FollowLogsRequest, StepRunner_FollowLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method FollowLogs not implemented")
}
func (UnimplementedStepRunnerServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedStepRunnerServer) RunUp(StepRunner_RunUpServer) error {
	return status.Errorf(codes.Unimplemented, "method RunUp not implemented")
}
func (UnimplementedStepRunnerServer) mustEmbedUnimplementedStepRunnerServer() {}

// UnsafeStepRunnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepRunnerServer will
// result in compilation errors.
type UnsafeStepRunnerServer interface {
	mustEmbedUnimplementedStepRunnerServer()
}

func RegisterStepRunnerServer(s grpc.ServiceRegistrar, srv StepRunnerServer) {
	s.RegisterService(&StepRunner_ServiceDesc, srv)
}

func _StepRunner_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_FollowSteps_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowStepsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).FollowSteps(m, &stepRunnerFollowStepsServer{stream})
}

type StepRunner_FollowStepsServer interface {
	Send(*FollowStepsResponse) error
	grpc.ServerStream
}

type stepRunnerFollowStepsServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowStepsServer) Send(m *FollowStepsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_FollowLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FollowLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StepRunnerServer).FollowLogs(m, &stepRunnerFollowLogsServer{stream})
}

type StepRunner_FollowLogsServer interface {
	Send(*FollowLogsResponse) error
	grpc.ServerStream
}

type stepRunnerFollowLogsServer struct {
	grpc.ServerStream
}

func (x *stepRunnerFollowLogsServer) Send(m *FollowLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _StepRunner_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepRunnerServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepRunner_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepRunnerServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepRunner_RunUp_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StepRunnerServer).RunUp(&stepRunnerRunUpServer{stream})
}

type StepRunner_RunUpServer interface {
	Send(*RunUpRequest) error
	Recv() (*RunUpResponse, error)
	grpc.ServerStream
}

type stepRunnerRunUpServer struct {
	grpc.ServerStream
}

func (x *stepRunnerRunUpServer) Send(m *RunUpRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *stepRunnerRunUpServer) Recv() (*RunUpResponse, error) {
	m := new(RunUpResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StepRunner_ServiceDesc is the grpc.ServiceDesc for StepRunner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepRunner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepRunner",
	HandlerType: (*StepRunnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _StepRunner_Run_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StepRunner_Close_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _StepRunner_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FollowSteps",
			Handler:       _StepRunner_FollowSteps_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FollowLogs",
			Handler:       _StepRunner_FollowLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RunUp",
			Handler:       _StepRunner_RunUp_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "step.proto",
}

const (
	StepLogger_Log_FullMethodName       = "/proto.StepLogger/Log"
	StepLogger_AddFilter_FullMethodName = "/proto.StepLogger/AddFilter"
)

// StepLoggerClient is the client API for StepLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepLoggerClient interface {
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	AddFilter(ctx context.Context, in *AddFilterRequest, opts ...grpc.CallOption) (*AddFilterResponse, error)
}

type stepLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewStepLoggerClient(cc grpc.ClientConnInterface) StepLoggerClient {
	return &stepLoggerClient{cc}
}

func (c *stepLoggerClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, StepLogger_Log_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stepLoggerClient) AddFilter(ctx context.Context, in *AddFilterRequest, opts ...grpc.CallOption) (*AddFilterResponse, error) {
	out := new(AddFilterResponse)
	err := c.cc.Invoke(ctx, StepLogger_AddFilter_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepLoggerServer is the server API for StepLogger service.
// All implementations must embed UnimplementedStepLoggerServer
// for forward compatibility
type StepLoggerServer interface {
	Log(context.Context, *LogRequest) (*LogResponse, error)
	AddFilter(context.Context, *AddFilterRequest) (*AddFilterResponse, error)
	mustEmbedUnimplementedStepLoggerServer()
}

// UnimplementedStepLoggerServer must be embedded to have forward compatible implementations.
type UnimplementedStepLoggerServer struct {
}

func (UnimplementedStepLoggerServer) Log(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedStepLoggerServer) AddFilter(context.Context, *AddFilterRequest) (*AddFilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFilter not implemented")
}
func (UnimplementedStepLoggerServer) mustEmbedUnimplementedStepLoggerServer() {}

// UnsafeStepLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepLoggerServer will
// result in compilation errors.
type UnsafeStepLoggerServer interface {
	mustEmbedUnimplementedStepLoggerServer()
}

func RegisterStepLoggerServer(s grpc.ServiceRegistrar, srv StepLoggerServer) {
	s.RegisterService(&StepLogger_ServiceDesc, srv)
}

func _StepLogger_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepLoggerServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepLogger_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepLoggerServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StepLogger_AddFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepLoggerServer).AddFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepLogger_AddFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepLoggerServer).AddFilter(ctx, req.(*AddFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepLogger_ServiceDesc is the grpc.ServiceDesc for StepLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepLogger",
	HandlerType: (*StepLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _StepLogger_Log_Handler,
		},
		{
			MethodName: "AddFilter",
			Handler:    _StepLogger_AddFilter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "step.proto",
}

const (
	StepCompiler_Compile_FullMethodName = "/proto.StepCompiler/Compile"
)

// StepCompilerClient is the client API for StepCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StepCompilerClient interface {
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type stepCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewStepCompilerClient(cc grpc.ClientConnInterface) StepCompilerClient {
	return &stepCompilerClient{cc}
}

func (c *stepCompilerClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, StepCompiler_Compile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StepCompilerServer is the server API for StepCompiler service.
// All implementations must embed UnimplementedStepCompilerServer
// for forward compatibility
type StepCompilerServer interface {
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	mustEmbedUnimplementedStepCompilerServer()
}

// UnimplementedStepCompilerServer must be embedded to have forward compatible implementations.
type UnimplementedStepCompilerServer struct {
}

func (UnimplementedStepCompilerServer) Compile(context.Context, *CompileRequest) (*CompileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedStepCompilerServer) mustEmbedUnimplementedStepCompilerServer() {}

// UnsafeStepCompilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StepCompilerServer will
// result in compilation errors.
type UnsafeStepCompilerServer interface {
	mustEmbedUnimplementedStepCompilerServer()
}

func RegisterStepCompilerServer(s grpc.ServiceRegistrar, srv StepCompilerServer) {
	s.RegisterService(&StepCompiler_ServiceDesc, srv)
}

func _StepCompiler_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StepCompilerServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StepCompiler_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StepCompilerServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StepCompiler_ServiceDesc is the grpc.ServiceDesc for StepCompiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StepCompiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StepCompiler",
	HandlerType: (*StepCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _StepCompiler_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "step.proto",
}
