// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "reflect"

type InputDefault interface{}

type OutputDefault interface{}

// Output describes a single step output.
type Outputs struct {
	// Default is the default output value.
	Default OutputsDefault `json:"default,omitempty" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// Sensitive implies the output is of sensitive nature and effort should be made
	// to prevent accidental disclosure.
	Sensitive *bool `json:"sensitive,omitempty" yaml:"sensitive,omitempty" mapstructure:"sensitive,omitempty"`

	// Type is the value type of the output.
	Type *OutputsType `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// Default is the default output value.
type OutputsDefault interface{}

type OutputsType string

const OutputsTypeArray OutputsType = "array"
const OutputsTypeBoolean OutputsType = "boolean"
const OutputsTypeNumber OutputsType = "number"
const OutputsTypeRawString OutputsType = "raw_string"
const OutputsTypeStepResult OutputsType = "step_result"
const OutputsTypeString OutputsType = "string"
const OutputsTypeStruct OutputsType = "struct"

var enumValues_OutputsType = []interface{}{
	"raw_string",
	"string",
	"number",
	"boolean",
	"struct",
	"array",
	"step_result",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OutputsType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OutputsType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_OutputsType, v)
	}
	*j = OutputsType(v)
	return nil
}

// Spec is a document describing the interface of the step.
type SpecJson struct {
	// Spec contains the inputs and outputs of the step.
	Spec *SpecJsonSpec `json:"spec,omitempty" yaml:"spec,omitempty" mapstructure:"spec,omitempty"`
}

// Spec contains the inputs and outputs of the step.
type SpecJsonSpec struct {
	// Input describes a single step input.
	Inputs *SpecJsonSpecInputs `json:"inputs,omitempty" yaml:"inputs,omitempty" mapstructure:"inputs,omitempty"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs SpecJsonSpecOutputs `json:"outputs,omitempty" yaml:"outputs,omitempty" mapstructure:"outputs,omitempty"`
}

// Input describes a single step input.
type SpecJsonSpecInputs struct {
	// Default is the default input value. Its type must match `type`.
	Default SpecJsonSpecInputsDefault `json:"default,omitempty" yaml:"default,omitempty" mapstructure:"default,omitempty"`

	// Sensitive implies the input is of sensitive nature and effort should be made to
	// prevent accidental disclosure.
	Sensitive *bool `json:"sensitive,omitempty" yaml:"sensitive,omitempty" mapstructure:"sensitive,omitempty"`

	// Type is the value type of the input.
	Type *SpecJsonSpecInputsType `json:"type,omitempty" yaml:"type,omitempty" mapstructure:"type,omitempty"`
}

// Default is the default input value. Its type must match `type`.
type SpecJsonSpecInputsDefault interface{}

type SpecJsonSpecInputsType string

const SpecJsonSpecInputsTypeArray SpecJsonSpecInputsType = "array"
const SpecJsonSpecInputsTypeBoolean SpecJsonSpecInputsType = "boolean"
const SpecJsonSpecInputsTypeNumber SpecJsonSpecInputsType = "number"
const SpecJsonSpecInputsTypeString SpecJsonSpecInputsType = "string"
const SpecJsonSpecInputsTypeStruct SpecJsonSpecInputsType = "struct"

var enumValues_SpecJsonSpecInputsType = []interface{}{
	"string",
	"number",
	"boolean",
	"struct",
	"array",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *SpecJsonSpecInputsType) UnmarshalJSON(b []byte) error {
	var v string
	if err := json.Unmarshal(b, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_SpecJsonSpecInputsType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_SpecJsonSpecInputsType, v)
	}
	*j = SpecJsonSpecInputsType(v)
	return nil
}

type SpecJsonSpecOutputs interface{}

type StringOutputsUnion interface{}
