// Code generated by goyacc -p expr -o expr_parser.gen.go expr_parser.y. DO NOT EDIT.

//line expr_parser.y:2
package evaluator

import __yyfmt__ "fmt"

//line expr_parser.y:2

import "gitlab.com/gitlab-org/step-runner/pkg/internal/expression/value"

//line expr_parser.y:7
type exprSymType struct {
	yys      int
	id       string
	number   int64
	str      string
	expr     Node
	exprList []Node
}

const ID = 57346
const NUMBER = 57347
const STRING = 57348
const EQUAL = 57349
const NOT_EQUAL = 57350
const DOT = 57351
const OPEN = 57352
const CLOSE = 57353
const AND = 57354
const OR = 57355
const SEPARATOR = 57356

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"ID",
	"NUMBER",
	"STRING",
	"EQUAL",
	"NOT_EQUAL",
	"DOT",
	"OPEN",
	"CLOSE",
	"AND",
	"OR",
	"SEPARATOR",
}

var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16

//line yacctab:1
var exprExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 33

var exprAct = [...]int8{
	2, 6, 28, 11, 12, 27, 7, 8, 9, 5,
	26, 17, 10, 24, 4, 20, 21, 25, 7, 8,
	9, 16, 19, 22, 10, 15, 18, 23, 29, 14,
	13, 3, 1,
}

var exprPact = [...]int16{
	14, -1000, -1000, -10, -8, 22, 16, 11, -1000, -1000,
	14, 14, 14, 14, 14, 19, 2, -1, -8, 22,
	16, 16, -1000, -9, -1000, -1000, -1000, 14, -1000, -1000,
}

var exprPgo = [...]int8{
	0, 32, 0, 31, 14, 9, 1, 27,
}

var exprR1 = [...]int8{
	0, 1, 7, 7, 2, 3, 3, 4, 4, 5,
	5, 5, 6, 6, 6, 6, 6, 6, 6,
}

var exprR2 = [...]int8{
	0, 1, 3, 1, 1, 3, 1, 3, 1, 3,
	3, 1, 1, 1, 1, 3, 3, 4, 3,
}

var exprChk = [...]int16{
	-1000, -1, -2, -3, -4, -5, -6, 4, 5, 6,
	10, 13, 12, 8, 7, 9, 10, -2, -4, -5,
	-6, -6, 4, -7, 11, -2, 11, 14, 11, -2,
}

var exprDef = [...]int8{
	0, -2, 1, 4, 6, 8, 11, 12, 13, 14,
	0, 0, 0, 0, 0, 0, 0, 0, 5, 7,
	9, 10, 16, 0, 18, 3, 15, 0, 17, 2,
}

var exprTok1 = [...]int8{
	1,
}

var exprTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14,
}

var exprTok3 = [...]int8{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(exprPact[state])
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && int(exprChk[int(exprAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || int(exprExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := int(exprExca[i])
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(exprTok1[0])
		goto out
	}
	if char < len(exprTok1) {
		token = int(exprTok1[char])
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = int(exprTok2[char-exprPrivate])
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = int(exprTok3[i+0])
		if token == char {
			token = int(exprTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(exprTok2[1]) /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = int(exprPact[exprstate])
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = int(exprAct[exprn])
	if int(exprChk[exprn]) == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = int(exprDef[exprstate])
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && int(exprExca[xi+1]) == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = int(exprExca[xi+0])
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = int(exprExca[xi+1])
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = int(exprPact[exprS[exprp].yys]) + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = int(exprAct[exprn]) /* simulate a shift of "error" */
					if int(exprChk[exprstate]) == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= int(exprR2[exprn])
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = int(exprR1[exprn])
	exprg := int(exprPgo[exprn])
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = int(exprAct[exprg])
	} else {
		exprstate = int(exprAct[exprj])
		if int(exprChk[exprstate]) != -exprn {
			exprstate = int(exprAct[exprg])
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:25
		{
			exprlex.(*exprLexerImpl).result = exprDollar[1].expr
		}
	case 2:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:30
		{
			exprVAL.exprList = append(exprDollar[1].exprList, exprDollar[3].expr)
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:31
		{
			exprVAL.exprList = []Node{exprDollar[1].expr}
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:33
		{
			exprVAL.expr = exprDollar[1].expr
		}
	case 5:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:36
		{
			exprVAL.expr = &nodeOr{left: exprDollar[1].expr, right: exprDollar[3].expr}
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:37
		{
			exprVAL.expr = exprDollar[1].expr
		}
	case 7:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:40
		{
			exprVAL.expr = &nodeAnd{left: exprDollar[1].expr, right: exprDollar[3].expr}
		}
	case 8:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:41
		{
			exprVAL.expr = exprDollar[1].expr
		}
	case 9:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:44
		{
			exprVAL.expr = &nodeCompareNotEquals{left: exprDollar[1].expr, right: exprDollar[3].expr}
		}
	case 10:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:45
		{
			exprVAL.expr = &nodeCompareEquals{left: exprDollar[1].expr, right: exprDollar[3].expr}
		}
	case 11:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:46
		{
			exprVAL.expr = exprDollar[1].expr
		}
	case 12:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:49
		{
			exprVAL.expr = &nodeDig{expr: &nodeContext{}, key: exprDollar[1].id}
		}
	case 13:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:50
		{
			exprVAL.expr = &nodeValue{value: value.ToValue(exprDollar[1].number)}
		}
	case 14:
		exprDollar = exprS[exprpt-1 : exprpt+1]
//line expr_parser.y:51
		{
			exprVAL.expr = &nodeValue{value: value.ToValue(exprDollar[1].str)}
		}
	case 15:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:52
		{
			exprVAL.expr = exprDollar[2].expr
		}
	case 16:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:53
		{
			exprVAL.expr = &nodeDig{expr: exprDollar[1].expr, key: exprDollar[3].id}
		}
	case 17:
		exprDollar = exprS[exprpt-4 : exprpt+1]
//line expr_parser.y:54
		{
			exprVAL.expr = &nodeCall{expr: &nodeContext{}, method: exprDollar[1].id, args: exprDollar[3].exprList}
		}
	case 18:
		exprDollar = exprS[exprpt-3 : exprpt+1]
//line expr_parser.y:55
		{
			exprVAL.expr = &nodeCall{expr: &nodeContext{}, method: exprDollar[1].id}
		}
	}
	goto exprstack /* stack new state and value */
}
