spec:
  inputs:
    action:
      type: string
    inputs:
      type: struct
    docker_host:
      type: string
    docker_socket_file:
      type: string
    action_runner_image:
      type: string
    action_image:
      type: string
    env_file:
      type: string
    work_dir:
      type: string
  outputs: delegate
---
env:
  DOCKER_HOST: "${{ inputs.docker_host }}"
exec:
  work_dir: "${{ inputs.work_dir }}"
  command:
    - docker
    - run
    - --rm
    - -i
    - --env-file
    - "${{ inputs.env_file }}"
    - -w
    - "${{ inputs.work_dir }}"
    - -v
    - "${{ inputs.work_dir }}:${{ inputs.work_dir }}"
    - -v
    - "${{ output_file }}:${{ output_file }}"
    - -v
    - "${{ inputs.docker_socket_file }}:${{ inputs.docker_socket_file }}"
    - "${{ inputs.action_runner_image }}"
    - --action
    - "${{ inputs.action }}"
    - --action-image
    - "${{ inputs.action_image }}"
    - --inputs
    - "${{ inputs.inputs }}"
    - --output-file
    - "${{ output_file }}"
