
go-fmt:
  stage: test
  image: golang:$GO_VERSION
  script:
    - make go-fmt
    - git diff --exit-code

go-lint:
  stage: test
  image: golang:${GO_VERSION}-alpine
  script:
    - apk add git make
    - make go-lint

check-generated:
  stage: test
  image: golang:$GO_VERSION
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - make check-generated

go-test:
  stage: test
  image: golang:${GO_VERSION}
  before_script:
    - make build-builtin-steps
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum --junitfile=report.xml
                --format=testname
                --rerun-fails=2
                --packages="./..."
                --jsonfile=tmp.json.log
                --post-run-command="bash -c 'echo; echo Slowest tests; gotestsum tool slowest --num 10 --jsonfile tmp.json.log'"
                -- -race ./...
  artifacts:
    when: always
    reports:
      junit: report.xml

changelog-format:
  stage: test
  image: registry.gitlab.com/gitlab-org/step-runner:v0
  run:
    - name: changelog
      step: ./.gitlab/steps/changelog
      inputs:
        changelog: "${{job.CI_PROJECT_DIR}}/CHANGELOG.md"
        echo_latest: true
