
go-fmt:
  stage: test
  image: golang:$GO_VERSION
  script:
    - make go-fmt
    - git diff --exit-code

go-lint:
  stage: test
  image: golangci/golangci-lint:v1.63.4
  script:
    - golangci-lint run -v --timeout 5m

check-generated:
  stage: test
  image: golang:$GO_VERSION
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - make check-generated

go-test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - go test -race ./...

changelog-format:
  stage: test
  image: registry.gitlab.com/gitlab-org/step-runner:v0
  run:
    - name: changelog
      step: ./.gitlab/steps/changelog
      inputs:
        changelog: "${{job.CI_PROJECT_DIR}}/CHANGELOG.md"
        echo_latest: true
