
go-fmt:
  stage: test
  image: golang:$GO_VERSION
  script:
    - make go-fmt
    - git diff --exit-code

go-lint:
  stage: test
  image: golangci/golangci-lint:v1.59.1
  script:
    - golangci-lint run -v --timeout 5m

check-generated:
  stage: test
  image: golang:$GO_VERSION
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - make check-generated

go-test:
  stage: test
  image: golang:$GO_VERSION
  script:
    - go test -race ./...
